sudo: required
language: node_js
dist: trusty

os:
  - osx

node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
- npm install
- npm run postinstall

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
- sleep 3

script:
- npm run pretest
- npm run lint
- npm run compile
- npm run dist

