sudo: required
language: node_js
dist: trusty

os:
  - osx

node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
- sudo spctl --master-disable
- npm install
- npm run postinstall

before_script:
- npm run pretest

script:
- npm run pretest
- npm run lint
- npm run compile
- npm run publish:osx

