sudo: false

language: node_js

os:
  - linux
  - osx

node_js:
  - "5"
  - "6"

cache:
  directories:
    - node_modules

install:
- npm install
- npm install coveralls

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- npm run lint
- npm run build

after_script:
- npm run coverage
- cat ./c coverage/lcov.info | coveralls
