sudo: required
language: node_js
dist: trusty

os:
  - linux
  - osx

node_js:
  - "5"
  - "6"

cache:
  directories:
    - node_modules

install:
- npm install
- npm install coveralls
- npm run postinstall

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
- sleep 3

script:
- npm run pretest
- npm run lint
- npm run build

after_script:
- npm run coverage
- cat ./c coverage/lcov.info | coveralls
